src/pages/index.tsx

FE-3: modify index page

---

src/app/_providers/partyroom-connection.provider.tsx
src/app/parties/(room)/[id]/temp-avatars.tsx
src/app/parties/layout.tsx
src/app/settings/profile/layout.tsx
src/entities/me/api/use-fetch-me.query.ts
src/entities/me/index.ts
src/features/edit-profile-avatar/lib/selected-avatar-state.provider.tsx
src/features/edit-profile-bio/ui/v1.component.tsx
src/features/edit-profile-bio/ui/v2-edit.component.tsx
src/features/edit-profile-bio/ui/v2-view.component.tsx
src/features/partyroom/create/ui/form.component.tsx
src/widgets/sidebar/ui/sidebar.component.tsx

[이전 PR](https://github.com/pfplay/pfplay-web/pull/126)에서 제거했던 useSuspenseQuery 사용부를 일부 복구합니다. me가 nullable일 수 있는 페이지(ex - home)에서도 suspense fetch를 사용했던게 이전 PR 에러의 원인으로 예상됩니다.

feat(entities/me): suspense fetch me 복구

---

src/shared/lib/decorators/singleton/README.md
src/shared/lib/decorators/singleton/index.ts
src/shared/lib/decorators/singleton/singleton.decorator.ts

클래스가 싱글톤으로 동작하도록 하는 데코레이터를 추가합니다.
```tsx
import { Singleton } from '@shared/lib/decorators/singleton';
@Singleton
class User {
constructor(private name: string) {}
public sayName() {
console.log(`My name is ${this.name}`);
}
}
// ...
let user = new User('Bob');
let secondUser = new User('not Bob'); // appear warning about initiate twice
user.sayName(); // "My name is Bob"
secondUser.sayName(); // still "My name is Bob"
```

feat(shared/lib): signleton decorator 추가

---

src/entities/me/api/use-fetch-me.query.ts
src/features/edit-profile-avatar/api/use-fetch-avatar-bodies.query.ts
src/features/edit-profile-avatar/api/use-fetch-avatar-faces.query.ts
src/features/edit-profile-avatar/api/use-update-my-avatar.mutation.ts
src/features/edit-profile-bio/api/use-update-my-bio.mutation.ts
src/features/partyroom/create/ui/form.component.tsx
src/features/partyroom/list/api/use-fetch-partyrooms.query.ts
src/features/playlist/add-musics/api/use-add-playlist-music.mutation.ts
src/features/playlist/add-musics/api/use-search-musics.query.ts
src/features/playlist/add/api/use-create-playlist.mutation.ts
src/features/playlist/edit/api/use-update-playlist.mutation.ts
src/features/playlist/list-musics/api/use-fetch-playlist-musics.query.ts
src/features/playlist/list/api/use-fetch-playlists.query.ts
src/features/playlist/remove-musics/api/use-remove-playlist-music.mutation.ts
src/features/playlist/remove/api/use-remove-playlist.mutation.ts
src/features/sign-in/by-google/lib/use-sign-in-for-dev.hook.tsx
src/features/sign-in/by-google/lib/use-sign-in.hook.tsx
src/features/sign-out/api/use-sign-out.mutation.ts
src/shared/api/http/client/client.ts
src/shared/api/http/services/parties.ts
src/shared/api/http/services/playlists.ts
src/shared/api/http/services/users.ts
tsconfig.json

각종 데코레이터 사용을 위해 기존 shared/api 하위의 HTTP service 객체들을 클래스화합니다.
추가로, axios instance 또한 추상화 합니다.

refactor(shared/api): Service 객체 클래스화

---

.storybook/_providers/mock-stores.provider.tsx
.storybook/main.ts
.storybook/preview.tsx
package.json
src/app/layout.tsx
src/entities/current-partyroom/lib/handle-subscription-event.ts
src/entities/current-partyroom/lib/subscription-callbacks/use-aggregation-callback.hook.ts
src/entities/current-partyroom/lib/subscription-callbacks/use-deactivation-callback.hook.ts
src/entities/current-partyroom/lib/subscription-callbacks/use-playback-callback.hook.ts
src/widgets/partyroom-display-board/ui/display-board.component.tsx
src/widgets/partyroom-display-board/ui/parts/action-buttons.component.tsx
src/widgets/partyroom-display-board/ui/parts/notice.component.tsx
src/widgets/partyroom-display-board/ui/parts/video-title.component.tsx
src/widgets/partyroom-display-board/ui/parts/video.component.tsx
yarn.lock

feat: 파티룸 전광판 스토어 연동 및 관련 소켓 이벤트 핸들러 구현

---

.storybook/_providers/mock-query-client.provider.tsx
.storybook/preview.tsx
src/entities/current-partyroom/index.ts
src/entities/current-partyroom/model/playback.model.test.ts
src/entities/current-partyroom/model/playback.model.ts
src/features/partyroom/complete-playback/api/use-complete-playback.mutation.ts
src/features/partyroom/complete-playback/index.ts
src/shared/api/http/types/partyrooms.ts
src/widgets/partyroom-display-board/ui/display-board.stories.tsx
src/widgets/partyroom-display-board/ui/parts/video.component.tsx

https://github.com/user-attachments/assets/649aa016-daf8-4b49-9b6f-7d15297a4457

feat(widgets/partyroom-display-board): 전광판 비디오 API 연결 및 고도화

---

src/features/playlist/list/ui/editable-list.component.tsx
src/shared/ui/components/checkbox/checkbox.component.tsx

Grab playlist 일 경우 정책 상 이름 수정 및 삭제가 불가능하므로, 플레이리스트 수정 모드에서 수정 버튼과 삭제를 위한 체크박스를 disabled 처리합니다.
체크박스와 리스트 아이템 disabled에 대한 디자인어 피그마에 없어 일단 임의 처리 했고, [논의](https://pfplay.slack.com/archives/C03QTFBU8QG/p1722682306376729) 후 수정 예정입니다.

feat(features/playlist/list): Grab 플레이리스트일 경우 수정 및 삭제 버튼 disabled 처리

---

src/app/parties/(room)/[id]/member-avatars.tsx
src/entities/current-partyroom/lib/subscription-callbacks/use-access-callback.hook.ts
src/entities/current-partyroom/lib/subscription-callbacks/use-notice-callback.hook.ts
src/entities/current-partyroom/lib/subscription-callbacks/use-playback-callback.hook.ts
src/entities/current-partyroom/model/current-partyroom.model.ts
src/entities/current-partyroom/model/current-partyroom.store.ts
src/entities/current-partyroom/model/playback.model.test.ts
src/entities/current-partyroom/model/playback.model.ts
src/features/partyroom/enter/api/use-enter-partyroom.mutation.ts
src/features/partyroom/enter/api/use-fetch-notice.query.ts
src/shared/api/http/query-keys.ts
src/shared/api/http/services/partyrooms.ts
src/shared/api/http/types/partyrooms.ts
src/shared/api/websocket/types/partyroom.ts
src/shared/lib/functions/pick.test.ts
src/shared/lib/functions/pick.ts
src/widgets/partyroom-display-board/ui/display-board.stories.tsx
src/widgets/partyroom-display-board/ui/parts/notice.component.tsx

feat: API 스펙 변경 대응

---

package.json
src/app/docs/_ui/article-table.component.tsx
src/shared/ui/components/display-option-menu-on-hover-listener/display-option-menu-on-hover-listener.component.tsx
src/shared/ui/components/icon-menu/icon-menu.component.tsx
src/shared/ui/components/menu/menu-button.component.tsx
src/shared/ui/components/menu/menu-item-panel.component.tsx
src/shared/ui/components/typography/typography.component.tsx
src/widgets/layouts/ui/header.component.tsx
yarn.lock

- Headless ui 버전업에 따른 Menu 및 하위 컴포넌트들 리팩토링
- Item 위에 hover, click 여부에 따라 MenuPanel render 이슈 수정
N/A
N/A
N/A

Refactor:  menu component according to headlessui version up

---

src/shared/ui/foundation/theme.ts
src/widgets/partyroom-avatars/ui/avatars.component.tsx

화면 신축에 상관 없이 파티룸 내 아바타들의 위치를 파티룸 배경 이미지의 특정 위치에 항상 고정되도록 합니다.

feat(widgets/partyroom-avatars): 화면 신축과 상관 없이 배경 내 동일한 위치에 아바타들 상시 고정

---

src/shared/api/http/types/partyrooms.ts
src/shared/api/http/types/users.ts
src/widgets/partyroom-chat-panel/ui/chat-item.component.tsx
src/widgets/sidebar/ui/sidebar.component.tsx

face가 없는 아바타를 위한 프로필 이미지인 [avatarIconUri](https://pfplay.slack.com/archives/C051ZQSV205/p1720950963412789)를 추가 및 반영합니다.
[추가 논의 스레드](https://pfplay.slack.com/archives/C051N8A0ZSB/p1725085333716649)

feat: avatarIconUri 누락된 곳 추가 및 적용

---

src/entities/current-partyroom/index.ts
src/entities/current-partyroom/model/member.model.ts

파티룸 멤버들의 특정 액션 실행 가능 여부를 결정하는 클래스를 작성합니다.
``` ts
// Usage
import { Member } from '@/entities/current-partyroom';
// ...
const permissions = Member.Permissions.of(me.gradeType);
permissions.canAdjustGrade(targetGrade); // 타 유저의 등급을 조정할 수 있는가
permissions.adjustableGrades(); // 조정한다면, 선택할 수 있는 등급 목록
permissions.canSkipPlayback(); // 파티룸 플래이백을 스킵할 수 있는가
// ... etc
```

feat(entities/current-partyroom): 파티룸 멤버 권한에 대한 코어 클래스 작성

---

src/app/_providers/react-query.provider.tsx

query와 마찬가지로, mutation의 에러도 기본 글로벌 단에서 처리합니다.

chore(app): mutation error도 글로벌에서 처리

---

src/entities/current-partyroom/model/member.model.ts

* permissons에 잘못된 조건문 수정
* Flyweight 패턴 적용하여 최적화

fix(entities/current-partyroom): permissons에 잘못된 조건문 수정, 최적화

---

src/entities/current-partyroom/model/chat-message.model.ts
src/entities/current-partyroom/model/member.model.ts
src/features/partyroom/adjust-grade/api/use-adjust-grade.mutation.ts
src/features/partyroom/adjust-grade/config/grade-type-label.ts
src/features/partyroom/adjust-grade/index.ts
src/features/partyroom/adjust-grade/lib/use-adjust-grade.hook.tsx
src/features/partyroom/adjust-grade/lib/use-select-grade.hook.tsx
src/features/partyroom/exit/api/use-exit-partyroom.mutation.ts
src/shared/api/http/query-keys.ts
src/shared/api/http/services/partyrooms.ts
src/shared/api/http/types/partyrooms.ts
src/shared/ui/components/dialog/use-dialog.hook.tsx
src/shared/ui/components/display-option-menu-on-hover-listener/display-option-menu-on-hover-listener.component.tsx
src/shared/ui/components/menu/menu-item-panel.component.tsx
src/shared/ui/components/user-list-item/user-list-item.component.tsx
src/widgets/partyroom-chat-panel/ui/authority-headset.component.tsx
src/widgets/partyroom-chat-panel/ui/chat-item.component.tsx
src/widgets/partyroom-chat-panel/ui/partyroom-chat-panel.component.tsx

https://github.com/user-attachments/assets/a8bdcbe5-050a-4ed2-ac4a-39d0776ff7da
* 권한 변경에 대한 웹소켓 이벤트 추가되면 대응

feat: 파티룸 grade 조정 기능

---

src/entities/current-partyroom/model/current-partyroom.model.ts
src/entities/current-partyroom/model/current-partyroom.store.ts
src/entities/current-partyroom/model/member.model.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-access-callback.hook.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-motion-callback.hook.ts
src/features/partyroom/enter/lib/use-enter-partyroom.ts
src/features/partyroom/evaluate-current-playback/api/use-evaluate-current-playback.mutation.ts
src/features/partyroom/evaluate-current-playback/index.ts
src/features/partyroom/grab-current-playback/api/use-grab-current-playback.mutation.ts
src/features/partyroom/grab-current-playback/index.ts
src/shared/api/http/services/partyrooms.ts
src/shared/api/http/types/partyrooms.ts
src/shared/api/websocket/types/partyroom.ts
src/widgets/partyroom-avatars/ui/avatars.component.tsx
src/widgets/partyroom-display-board/ui/display-board.stories.tsx
src/widgets/partyroom-display-board/ui/parts/action-button.component.tsx
src/widgets/partyroom-display-board/ui/parts/action-buttons.component.tsx
src/widgets/partyroom-display-board/ui/parts/video.component.tsx

파티룸 리액션 기능을 개발합니다.
모션은 백엔드 미개발 상태로 불완전하게 작동합니다.

feat: 파티룸 리액션 기능

---

src/app/parties/(room)/[id]/page.tsx
src/features/partyroom/get-summary/api/use-fetch-partyroom-summary.query.tsx
src/features/partyroom/get-summary/index.tsx
src/shared/api/http/query-keys.ts
src/shared/api/http/services/partyrooms.ts
src/shared/api/http/types/partyrooms.ts
src/widgets/partyroom-detail/index.ts
src/widgets/partyroom-detail/ui/partyroom-detail-button.tsx
src/widgets/partyroom-detail/ui/partyroom-detail-panel.tsx
src/widgets/partyroom-djing-dialog/ui/body.component.tsx

partyr detail 패널 및 share Dialog 완료 PR입니다.
- 복사 한 링크로 접근 시에 redirection 처리
N/A
- 현재 영문 설정시에  Copy link/ Copy complete text가 overflow되는 defect가 있는데요. 추후 i18n (en) Copy/Copied!로 변경 되면 btn text overflow 되는 ui defect 사라질 예정입니다.
N/A

Feat: 파티룸 정보 패널 및 공유 버튼 dialog

---

package.json
src/app/parties/(room)/[id]/page.tsx
src/widgets/partyroom-detail/ui/partyroom-detail-button.tsx
src/widgets/partyroom-detail/ui/partyroom-detail-panel.tsx
yarn.lock

Twitter 버튼을 통한 공유 링크 작업 PR입니다.
N/A
N/A
N/A

feat: share on twitter done

---

src/entities/partyroom-client/lib/handle-subscription-event.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-regulation-callback.hook.ts
src/shared/api/http/types/@enums.ts
src/shared/api/websocket/types/partyroom.ts

파티룸 권한 조정 이벤트를 처리합니다.
다음 스프린트
* 채팅 공지로 알리기
* 대상자에게 다이얼로그로 알리기

feat: 파티룸 권한 조정 이벤트 수신 시 members 업데이트

---

src/entities/partyroom-client/lib/subscription-callbacks/use-deactivation-callback.hook.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-playback-callback.hook.ts
src/entities/partyroom-client/lib/subscription-callbacks/utils/use-invalidate-djing-queue.hook.ts

플레이백 정보 변경 시 변경자 외 다른 유저의 디제잉 다이얼로그에 내용 반영되지 않는 문제를 수정합니다.

fix: 플레이백 정보 변경 시 변경자 외 다른 유저의 디제잉 다이얼로그에 내용 반영되지 않는 문제

---

src/entities/current-partyroom/model/crew.model.ts
src/features/partyroom/skip-playback/ui/skip-playback.tsx

-  나의 grade는 moderator 이상이고,  skip 할 유저의 grade가 나 보다 높은 등급을 가지고 있으면 skip 방지에 대한 로직 수정 PR입니다.
N/A
N/A
N/A

fix: 나의 grade는 moderator 이상이고 skip 할 유저의 grade가 나 보다 높은 등급을 가지고 있으면 skip 방지

---

src/app/parties/(room)/[id]/page.tsx
src/widgets/partyroom-display-board/ui/parts/action-buttons.component.tsx

refactor(display-board): 변수명 단순 명확하게 변경, prop추상화

---

src/shared/api/http/services/users.ts

fix(shared/api): 잘못된 api 경로 수정

---

src/features/partyroom/list-playback-history/api/use-fetch-playback-history.query.ts
src/features/partyroom/list-playback-history/index.ts
src/features/partyroom/list-playback-history/ui/list-item.component.tsx
src/features/partyroom/list-playback-history/ui/list-item.stories.tsx
src/features/partyroom/list-playback-history/ui/list.component.tsx
src/shared/api/http/__fixture__/playback-history.fixture.ts
src/shared/api/http/query-keys.ts
src/shared/api/http/services/partyrooms.ts
src/shared/api/http/types/partyrooms.ts

"최근 디제잉 목록" 패널에 들어갈 리스트 feature를 작성합니다.

feat(feature): list-playback-history

---

src/features/partyroom/enter/lib/use-enter-partyroom.ts

파티룸 입장 시 setupInfo fetch와 notice fetch를 cascade로 호출했는데, 병렬 호출하도록 합니다.

refactor(enter): notice와 setupInfo 동시 호출

---

src/widgets/partyroom-detail/ui/main-panel.component.tsx
src/widgets/partyroom-detail/ui/panel-header.component.tsx
src/widgets/partyroom-detail/ui/playback-history-panel.component.tsx
src/widgets/partyroom-detail/ui/trigger.tsx

feat(widgets/partyroom-detail): playback history 패널 작성

---

src/shared/api/http/types/partyrooms.ts
src/widgets/partyroom-djing-dialog/ui/body.component.tsx

필드명 변경에 대응합니다. 이 변경 이후로 이제 대기 등록 취소 버튼이 정상 노출됩니다.

feat(widgets/partyroom-djing-dialog): djId >> crewId 변경 대응

---

src/entities/current-partyroom/model/chat-message.model.ts
src/entities/current-partyroom/model/current-partyroom.model.ts
src/entities/current-partyroom/model/current-partyroom.store.ts
src/entities/partyroom-client/lib/partyroom-client.ts
src/features/partyroom/impose-penalty/lib/use-delete-chat-message.tsx
src/features/partyroom/impose-penalty/lib/use-impost-penalty.tsx
src/shared/api/http/types/partyrooms.ts
src/shared/api/websocket/types/partyroom.ts
src/widgets/partyroom-chat-panel/ui/chat-item.component.tsx
src/widgets/partyroom-chat-panel/ui/partyroom-chat-panel.component.tsx

chat, penalty api 새 규격 적용 PR입니다 
N/A
N/A
N/A

refactor: update ws api contract

---

src/entities/partyroom-client/lib/subscription-callbacks/use-crew-profile-callback.hook.ts

파티룸 내에서 특정 크루의 닉네임, 아바타 변경 시 모든 크루 클라이언트에 변경 내역을 실시간 반영하는 기능을 개발합니다.

feat(entities/partyroom-client): CrewProfileEvent 콜백 작성

---

src/entities/current-partyroom/model/crew.model.ts
src/features/partyroom/lock-djing-queue/api/use-lock-djing-queue.mutation.ts
src/features/partyroom/lock-djing-queue/index.ts
src/features/partyroom/lock-djing-queue/lib/use-can-lock-djing-queue.hook.ts
src/features/partyroom/lock-djing-queue/lib/use-lock-djing-queue.hook.ts
src/features/partyroom/unlock-djing-queue/api/use-unlock-djing-queue.mutation.ts
src/features/partyroom/unlock-djing-queue/index.ts
src/features/partyroom/unlock-djing-queue/lib/use-can-unlock-djing-queue.hook.ts
src/features/partyroom/unlock-djing-queue/lib/use-unlock-djing-queue.hook.ts
src/shared/api/http/services/partyrooms.ts
src/shared/api/http/types/partyrooms.ts
src/widgets/partyroom-djing-dialog/lib/djing-queue.context.tsx
src/widgets/partyroom-djing-dialog/ui/body.component.tsx
src/widgets/partyroom-djing-dialog/ui/dialog.component.tsx
src/widgets/partyroom-djing-dialog/ui/register-button.component.tsx

[화면 기획서](https://www.figma.com/design/9I5PR6OqN8cHJ7WVTOKe00/PFPlay-GUI-%EC%84%A4%EA%B3%84%EC%84%9C-%ED%95%A9%EB%B3%B8?node-id=1-134746&t=q0KKTsiXm22VJg2W-4)

feat: dj 대기열 잠금 및 잠금 해제 기능 구현

---

src/shared/api/http/services/users.ts

요청 url 틀려서 구글 로그인 안 되는 문제를 수정합니다

fix: 구글 로그인 안 되는 문제 수정

---

src/entities/current-partyroom/model/chat-message.model.ts
src/entities/current-partyroom/model/current-partyroom.model.ts
src/entities/current-partyroom/model/current-partyroom.store.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-chat-callback.hook.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-crew-penalty-callback.hook.ts
src/widgets/partyroom-chat-panel/ui/partyroom-chat-panel.component.tsx

* 미사용 타입 제거
* SystemChat에도 receivedAt 추가
* key prop에 사용하기 위함 
* appendChatMessage가 ChatMessageModel 자체를 받도록 변경
* 기존에 from="user" 고정이였는데, from="system" 메세지도 append 할 수 있도록 하기 위함
* 기존 파티룸 스토어 내 필드들에 주석 설명 추가
* 누락된 key prop 추가

chore: 채팅 모듈 손질

---

src/entities/partyroom-client/config/grade-type-label.ts
src/entities/partyroom-client/index.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-crew-grade-callback.hook.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-crew-penalty-callback.hook.ts
src/widgets/partyroom-chat-panel/ui/chat-item.component.tsx

grade 조정 이벤트 발생 시 system 채팅으로 전체에게 알립니다.

feat(entities/partyroom-client): grade 조정 시 채팅 공지

---

src/features/edit-profile-avatar/api/use-update-my-walllet.mutation.ts
src/features/edit-profile-avatar/ui/avatar-face-list.component.tsx
src/features/edit-profile-avatar/ui/connect-wallet-button.component.tsx

fix: 지갑 연동 시 api 호출 안하고 있음

---

src/shared/api/http/types/partyrooms.ts
src/widgets/partyroom-avatars/lib/use-assign-avatar-positions.hook.ts
src/widgets/partyroom-avatars/ui/avatars.component.tsx

PartyroomCrew에서 uid와 authority 제거되어 대응합니다

chore: PartyroomCrew에서 uid와 authority 제거된 것 대응

---

src/shared/api/http/services/partyrooms.ts

fix: 리액션 request url fix

---

src/shared/lib/functions/deep-equal.test.ts
src/shared/lib/functions/deep-equal.ts
src/widgets/partyroom-avatars/lib/use-assign-avatar-positions.hook.ts

crew의 추가 및 삭제에만 대응되어 있었습니다.
수정에도 대응되도록 합니다.

fix: crew 정보 수정 시 PartyroomAvatars 컴포넌트 상태에 반영 안되던 문제

---

src/entities/current-partyroom/model/crew.model.ts
src/features/partyroom/impose-penalty/lib/use-delete-chat-message.tsx
src/features/partyroom/impose-penalty/lib/use-impost-penalty.tsx
src/widgets/partyroom-chat-panel/ui/partyroom-chat-panel.component.tsx

feat: 패널티에 대한 권한 정의 및 적용

---

src/entities/current-partyroom/lib/alerts/use-penalty-alert.hook.tsx

feat: kick 또는 ban 시 로비로 추방

---

src/entities/partyroom-info/ui/form.component.tsx
src/features/partyroom/create/ui/form.component.tsx
src/features/partyroom/edit/ui/form.component.tsx
src/features/partyroom/edit/ui/trigger.component.tsx

파티룸 수정 시 다이얼로그 타이틀과 버튼 텍스트를 수정합니다

chore: 파티룸 수정 시 다이얼로그 타이틀과 버튼 텍스트 수정

---

src/widgets/partyroom-avatars/ui/avatars.component.tsx

feat: 디제이 항상 춤 추도록 함

---

src/features/edit-profile-avatar/ui/connect-wallet-button.component.tsx

지갑 연결 해제 시에도 api를 호출하여 extension(rainbow)과 DB 간 "지갑 연결 여부"를 동기화합니다.
https://github.com/user-attachments/assets/6fb67fae-ceaa-41bf-b528-b53563d2c125

feat(features/edit-profile-avatar): 지갑 연결 해제 시 api 호출

---

src/features/sign-out/lib/use-sign-out.hook.ts
src/shared/lib/localization/language-change-menu.component.tsx
src/shared/lib/localization/use-languages.hook.ts
src/shared/ui/components/dialog/dialog.component.tsx
src/shared/ui/components/dialog/index.ts
src/widgets/partyroom-detail/ui/main-panel.component.tsx
src/widgets/partyroom-detail/ui/use-open-setting-dialog.hook.tsx
src/widgets/partyroom-djing-dialog/ui/body.component.tsx
src/widgets/partyroom-djing-dialog/ui/empty-body.component.tsx

파티룸 detail 쪽 settings 버튼에 콜백을 연결합니다.
"가이드"에 관해선 [문의 중](https://pfplay.slack.com/archives/C03QTFBU8QG/p1731840284145439)이며, 별도 티켓으로 진행하겠습니다.
https://github.com/user-attachments/assets/f63ff98e-802c-4e0b-9155-fea507561c4e

feat(widgets/partyroom-detail): settings 버튼 콜백 작업 및 연결

---

scripts/svgr.js

svgr 스크립트를 windows에서도 호환되도록 수정합니다

fix: svgr 스크립트를 windows에서도 호환되도록 수정

---

src/app/(auth)/sign-in/page.tsx
src/features/sign-in/by-google/ui/sign-in-button-for-dev.component.tsx
src/features/sign-in/by-guest/api/use-sign-in.mutation.ts
src/features/sign-in/by-guest/index.ts
src/features/sign-in/by-guest/lib/use-sign-in.hook.tsx
src/shared/api/http/services/users.ts
src/shared/api/http/types/users.ts
src/shared/ui/components/dialog/dialog.component.tsx
src/shared/ui/components/dialog/dialog.stories.tsx

feat: 게스트 로그인 기능 작성

---

next-env.d.ts
package.json
yarn.lock

nextjs, webpack >> 취약점 수정 버전 반영
viem >> https://github.com/wevm/viem/issues/881 해결을 위한 버전 업

feat: 취약점 및 버그 수정을 위한 패키지 버전 업

---

package.json
src/app/_providers/wallet.provider.tsx
yarn.lock

chain을 mainnet으로 설정 시 [이슈](https://github.com/wevm/viem/issues/881)에 명시된 것과 같은 에러 발생하여, 임시 주석 처리
공교롭게도 개발 환경을 Windows로 변경한 후 부터 발견된 에러인데, OS와 관련 있을지도 확인 필요

fix: 지갑 연결 시 정보 가져올 때 알 수 없는 에러 발생하여 임시 조치

---

src/app/_providers/wallet.provider.tsx
src/entities/wallet/index.ts
src/entities/wallet/lib/use-global-wallet-sync.hook.ts
src/entities/wallet/lib/use-is-wallet-linked.hook.ts
src/entities/wallet/ui/connect-wallet.component.tsx
src/entities/wallet/ui/use-inform-wallet-linkage.hook.tsx
src/features/edit-profile-avatar/ui/avatar-face-list.component.tsx
src/features/partyroom/create/ui/card.component.tsx
src/features/playlist/add/ui/form.component.tsx
src/shared/api/http/services/partyrooms.ts
src/shared/api/http/services/playlists.ts
src/shared/ui/components/typography/typography.component.tsx

* ConnectWallet 마운트 여부에 상관 없이 지갑 연동을 항상 watch 합니다.
* 지갑 연동이 필요할 경우(플레이리스트 생성 제한, 파티룸 생성) 지갑 연동을 즉석에서 할 수 있도록 지원합니다.

feat: 지갑 연동 고도화, 지갑 연동 필요한 기능에 알림 반영

---

src/entities/partyroom-client/lib/handle-subscription-event.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-partyroom-close-callback.hook.ts
src/shared/api/websocket/types/partyroom.ts

파티룸 폐쇄 이벤트 (임의 추가)에 대한 콜백을 작성합니다.
로비로 나가기, 스토어 및 캐시 초기화, 폐쇄 알림

feat: 파티룸 폐쇄 이벤트 콜백 작성

---

package.json
public/icons/Action/icn_drag_and_drop.svg
src/entities/playlist/lib/playlist-action.context.tsx
src/features/playlist/list-tracks/ui/track.component.tsx
src/features/playlist/list-tracks/ui/track.stories.tsx
src/features/playlist/list-tracks/ui/tracks.component.tsx
src/features/playlist/move-track-to-the-other-playlist/api/use-change-track-order.mutation.ts
src/features/playlist/move-track-to-the-other-playlist/api/use-move-playlist-track.mutation.ts
src/features/playlist/move-track-to-the-other-playlist/index.ts
src/features/playlist/remove-track/api/use-remove-playlist-track.mutation.ts
src/shared/api/http/__fixture__/playlist-tracks.fixture.ts
src/shared/api/http/services/playlists.ts
src/shared/api/http/types/playlists.ts
src/widgets/my-playlist/lib/playlist-action.provider.tsx
yarn.lock

1. Playlist의 트랙 순서 변경 기능 구현
2. API 명세 변경사항 대응
- 플레이리스트 API 스펙 변경에 따른 인터페이스 수정
- 관련 타입 및 요청/응답 구조 업데이트
N/A
[dnd kit](https://dndkit.com/): Drag and drop library

[PF-53]feat: Playlist의 트랙 순서를 drag&drop 기능과 함께 변경

---

src/app/parties/(room)/[id]/page.tsx
src/entities/me/index.ts
src/entities/me/lib/use-is-guest.hook.tsx
src/features/sign-in/by-google/index.ts
src/features/sign-in/by-google/lib/use-inform-google-login.hook.tsx

게스트 로그인 상태로 djing 사용하려 할 시 구글 로그인 유도합니다.
리디렉션은 아쉽게도 현재 parties 고정입니다

feat: 게스트 로그인 상태로 djing 사용하려 할 시 구글 로그인 유도

---

src/app/parties/(room)/[id]/page.tsx
src/features/partyroom/share-link/index.ts
src/features/partyroom/share-link/lib/use-open-share-dialog.hook.tsx
src/features/playlist/add-tracks/ui/search-list-item.component.tsx
src/widgets/partyroom-detail/ui/main-panel.component.tsx
src/widgets/sidebar/ui/sidebar.component.tsx

feat: 파티룸 내 사이드바에 파티룸 공유 버튼 추가
