src/app/_providers/react-query.provider.tsx
src/shared/api/http/services/parties.ts
src/shared/api/http/services/playlists.ts
src/shared/api/http/services/users.ts

`queryFn: MyService.myMethod` 와 같이 사용할 경우 this 바인딩이 의도와 다르게 동작하는 문제를 수정하기 위해 모든 http 서비스 메서드를 prototype method >> instance method로 변경합니다.
각 서비스 인스턴스는 싱글톤이기에 instance method의 메모리 부하 문제 등은 걱정 없습니다.

fix(shared/api): http service들 this 바인딩 문제 수정

---

src/shared/ui/components/dialog/dialog.component.tsx
src/shared/ui/components/dialog/dialog.stories.tsx
src/shared/ui/components/dialog/use-dialog.hook.tsx

headless ui dialog의 onClose 동작이 dialog provider의 중첩 모달 스택 컨트롤 방식과 맞지 않아 생기는 문제였습니다.
내부를 까보진 않았지만, 아마 자식 요소를 제외한 모든 요소에 클릭 이벤트에 대해 onClose를 실행하는 것 같습니다.

fix(shared/ui/dialog): 중첩 모달 중 제일 상단 모달을 닫을 때 모든 모달이 닫혀버리는 문제 

---

src/widgets/partyroom-djing-dialog/ui/body.component.tsx

DJ를 단순 index가 아닌 orderNumber 순으로 나열

fix(widgets/partyroom-djing-dialog): DJ를 단순 index가 아닌 orderNumber 순으로 나열

---

src/entities/ui-state/model/ui-state.model.tsx
src/entities/ui-state/model/ui-state.store.tsx

zustand의 create 함수 세번째 인자는 getInitialState 라는 메서드를 가지고 있어서 초기 상태를 얻어올 수 있습니다.
기존에 초기 상태를 활용하기 위해 별도 변수로 빼뒀는데, getInitialState를 활용하도록 변경합니다.

refactor(entities/ui-state): initialValues를 zustand api 활용하도록 변경

---

src/features/playlist/list/api/use-fetch-playlists.query.ts
src/features/playlist/list/index.ts

현재 다국어 json은 FE에서 들고 있습니다. BE에선 grab playlist에 대해 FE의 언어가 무엇이든 상관없이(알 방법이 없으니) '그랩한 곡'이라는 문자를 name 필드에 고정으로 내려줍니다.
playlists 목록을 새로 받을 때, 그리고 언어가 변경될 때마다 현재 언어에 맞춰 grab playlist의 name 필드를 덮어씌우도록 설정합니다.

feat(features/playlist/list): 언어가 변경될 때마다 해당 언어에 맞춰 Grab Playlist의 이름 덮어씌우기

---

src/features/playlist/add-musics/ui/music-search.component.tsx
src/features/playlist/add-musics/ui/search-list-item.component.tsx

원래 음악 검색 후 "playlist에 추가" 버튼을 누르면 어떤 플레이리스트로 추가할지 선택하는 드롭다운 메뉴가 나옵니다.
위처럼 특정 플레이리스트를 선택하여 들어간 상태에선 음악 검색 후 "playlist에 추가" 버튼을 눌렀을 때 해당 플레이리스트로 곧장 음악이 추가되도록 UX를 개선합니다.

feat(features/playlist/add-musics): 선택된 플레이리스트가 있을 경우 해당 플레이리스트에 바로 음악 추가

---

src/features/playlist/list-musics/api/use-fetch-playlist-musics.query.ts
src/features/playlist/list-musics/ui/musics.component.tsx
src/features/playlist/remove-musics/api/use-remove-playlist-music.mutation.ts
src/widgets/my-playlist/ui/my-playlist.component.tsx

list-musics의 페이지네이션 요청 내 pageSize가 타겟 플레이리스트의 musicCount로 고정되어 있는데,
이 params 그대로 재요청을 하니 musicCount를 업데이트 하기 전 최신에 추가된 음악들이 응답에서 제외되던게 이유입니다.
pageSize를 항상 musics의 정책상 최대 개수로 설정하여 해결합니다.
추가로 playlists 업데이트 시 selectedPlaylist를 동기화합니다 (musicCount 정상 표시)

fix(features/list-musics): add music 성공 후 invalidateQueries가 실행되어도 추가된 음악이 화면에 반영되지 않던 문제

---

src/app/parties/(room)/[id]/layout.tsx
src/features/partyroom/exit/api/use-exit-partyroom.mutation.ts
src/features/partyroom/exit/index.ts

리스트로 돌아가는 것 외 다른 방법으로 탭 종료 시 exit api를 호출하도록 처리합니다.
컴퓨터 종료 등 비정상적인 케이스엔 대응하지 못합니다.

feat: 파티룸에서 브라우저 탭 종료 시 exit api 호출하도록 처리

---

.github/workflows/build-check.yml
.github/workflows/lint-check.yml
docs/README.md
package.json
yarn.lock

이 PR이 머지된 후, 아래 커맨드를 실행해주세요.
``` bash
nvm install --lts && nvm use --lts
n lts
```
``` bash
npm i -g yarn@latest
```
``` bash
cd YOUR_PROJECT_ROOT && yarn cache clean --all && rm -rf node_modules && yarn
```

chore: node 버전 lts로 업, yarn 버전 명시, peer dependencies 설치

---

src/features/partyroom/select-playlist-for-djing/ui/use-select-playlist.hook.tsx
src/shared/lib/hooks/use-portal-root.hook.ts

react 18이상에선 dev모드에서만 useEffect가 최초에 두 번 실행됩니다. (strict mode)
이 동작으로 "dev에선 동작하지만 production에선 동작하지 않는", 이 이슈 제목 같은 문제들이 발생했습니다. 이들을 찾아 수정합니다.

fix: production 환경에서 드로워 안 열리는 문제

---

src/shared/ui/components/select/select.component.tsx
src/shared/ui/components/select/select.stories.tsx

Select 컴포넌트를 개선합니다.
* 누락됐던 onChange prop 추가
* option 확장
* [prefix, suffix](https://www.figma.com/design/9I5PR6OqN8cHJ7WVTOKe00/PFPlay-GUI-%EC%84%A4%EA%B3%84%EC%84%9C-%ED%95%A9%EB%B3%B8?node-id=2257-25419&t=ArCFDtTTnbNHMs19-4) 추가
* label 타입 string >> ReactNode
* value 타입 string >> 제네릭
* classNames 제거 (className으로 대체)
* 요구처가 없는데 미리 확장하지 않는다는 맥락

feat(shared/ui/select): 누락된 onChange prop 추가, option 확장, 그 외 기타 개선

---

src/widgets/partyroom-display-board/ui/parts/action-buttons.component.tsx

플레이백 변경 시 전광판 통계 정보에 대한 FE 로컬 상태가 초기화 안되는 버그를 수정합니다.

fix: 곡 넘어가는데 좋아요,그랩,싫어요 상태 초기화 안되는 문제 수정

---

src/widgets/partyroom-avatars/lib/use-assign-avatar-positions.hook.ts
src/widgets/partyroom-avatars/model/avatar-position.model.ts
src/widgets/partyroom-avatars/ui/avatars.component.tsx

파티룸에 크루 입장 및 퇴장 시 페이지 컴포넌트의 crewsCount state에 변경이 생겨 리렌더가 발생합니다.
이 때 자식 컴포넌트인 PartyroomAvatars가 리렌더 되어 아바타들의 포지션이 재계산되는 문제를 방지하기 위해, 해당 컴포넌트를 React.memo로 감쌉니다.

fix(partyroom-avatars): 페이지 컴포넌트 리렌더 시 아바타들이 재배치되는 문제

---

src/features/playlist/add-musics/ui/search-input.component.tsx
src/shared/lib/functions/combine-ref.test.ts
src/shared/lib/functions/combine-ref.ts
src/shared/ui/components/input-number/input-number.component.tsx
src/shared/ui/components/input/input.component.tsx
src/shared/ui/components/textarea/textarea.component.tsx

외부에서 주입받은 ref와 로컬 ref를 합치고 싶을 때 아래와 같은 형식으로 사용했는데, 이를 유틸화하여 중복을 제거하고 테스트를 더해 안정성을 더합니다.
```tsx
ref={(node) => {
setRef(node);
if (typeof ref === 'function') {
ref(node);
} else if (ref) {
ref.current = node;
}
}}
```
* Input에 대한 작은 리팩터링 포함됩니다
* [리팩터링] css 선택자로 해결할 수 있는 걸 js로 해결하고 있었습니다. 이를 개선합니다. (onFocus + onBlur >> :focus-within)

refactor: combineRef 작성 및 적용 

---

src/features/partyroom/create/ui/form.component.tsx
src/shared/ui/components/input-number/input-number.component.tsx
src/shared/ui/components/input/input.component.tsx

Input과 InputNumber에 zod register가 ref로 set한 값이 안 보이거나 적용되지 않는 문제가 있었습니다.
* defaultValue 기본 값이 '' 라서 value가 항상 string이고, 이 때문에 zod register에서 ref로 set된 값은 리렌더 시 value에 덮어씌워집니다.
* 이전 ref는 RefCallback 이라 ref가 set되면 리렌더가 발생하며, 때문에 mount 시점에 ref로 set된 값이 곧바로 덮어씌워져 없어지며 마치 처음부터 zod register가 동작하지 않은 것처럼 보여지고 있었습니다.
* defaultValue 기본 값을 제거하여 해결합니다.

fix: zod register가 ref로 set한 값이 안 보이거나 적용되지 않는 문제

---

src/app/parties/(lobby)/page.tsx
src/features/partyroom/create/api/use-create-partyroom.mutation.ts
src/features/partyroom/create/model/form.model.ts
src/features/partyroom/create/ui/card.component.tsx
src/features/partyroom/create/ui/form.component.tsx
src/features/partyroom/list/ui/partyroom-card.component.tsx
src/shared/api/http/services/partyrooms.ts
src/shared/api/http/types/partyrooms.ts

파티룸 생성 기능을 작성합니다.
djing limit 필드는 기획상 placeholder로 기본 값을 보여준 뒤 submit 시점에 값이 비어있다면 기본 값을 넣어 api 요청을 쏴야합니다.
하지만 zod에서 number 필드에 대해 "비어있거나 3보다 클 때 valid" 라는 조건을 달성하는 법을 찾지 못해, placeholder가 아닌 defaultValue로 임의 처리합니다. 
#193

feat(features/create-partyroom): 파티룸 생성 기능 작성

---

src/app/parties/(room)/[id]/page.tsx
src/entities/current-partyroom/lib/use-chat.hook.ts
src/entities/current-partyroom/model/chat-message.model.ts
src/entities/current-partyroom/model/current-partyroom.model.ts
src/entities/current-partyroom/model/current-partyroom.store.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-crew-penalty-callback.hook.ts
src/features/partyroom/impose-penalty/lib/use-impost-penalty.tsx
src/widgets/partyroom-chat-panel/ui/partyroom-chat-panel.component.tsx
src/widgets/partyroom-detail/ui/use-open-share-dialog.hook.tsx
src/widgets/partyroom-djing-dialog/ui/penalty-notification-dialog.component.tsx

각 제재 요청이 완료 됐을 시 전파 받은 penaltyType에 따라 후속조치 [(화면기획서)](https://www.figma.com/design/9I5PR6OqN8cHJ7WVTOKe00/PFPlay-GUI-%EC%84%A4%EA%B3%84%EC%84%9C-%ED%95%A9%EB%B3%B8?node-id=1-97290&t=2ZnndhNHjOZLPoWf-4)
- CHAT_MESSAGE_REMOVAL일 경우 채팅 창에 삭제 요청된 메세지 삭제처리
- 나머지 제재에 대해선 제재 당한 유저에게 패널티 안내 dialog 띄어주기
- 현재 menuConfig에 모든 제재리스트들을 나열한 것을 디자인에 따라 메뉴 옵션에서 '제재' item을 눌렀을 시 모든 제재 아이템을 메뉴 옵션에 보여주는 식으로 변경해야합니다. 다른 브랜치에서 작업하겠습니다
N/A
N/A

feat: 각 제재 요청이 완료 됐을 시 전파 받은 penaltyType에 따라 후속조치

---

src/entities/current-partyroom/lib/use-chat.hook.ts
src/entities/current-partyroom/model/chat-message.model.ts
src/entities/current-partyroom/model/current-partyroom.model.ts
src/entities/current-partyroom/model/current-partyroom.store.ts
src/entities/partyroom-client/lib/subscription-callbacks/use-crew-penalty-callback.hook.ts
src/shared/config/max-message-amount.ts
src/shared/lib/chat/lib/chat.ts
src/shared/lib/chat/lib/circular-buffer-adapter.ts
src/shared/lib/chat/lib/circular-buffer.ts
src/shared/lib/chat/lib/observer-adapter.ts
src/shared/lib/chat/lib/observer.ts
src/shared/lib/chat/model/chat-message-listener.model.ts
src/shared/lib/chat/model/chat-messages.model.ts
src/widgets/partyroom-chat-panel/ui/chat-item.component.tsx
src/widgets/partyroom-chat-panel/ui/partyroom-chat-panel.component.tsx

zustand store에서 관리하던 updateMessage를 chat 클래스에 위임하고,  불필요해진 state들을 store 에서제거합니다.
N/A
N/A
N/A

refactor: delegate updateMessage method to chat class

---

src/app/layout.tsx
src/app/parties/(lobby)/page.tsx
src/app/parties/(room)/[id]/page.tsx
src/app/settings/avatar/page.tsx
src/app/settings/layout.tsx
src/features/edit-profile-avatar/index.ts
src/features/edit-profile-avatar/ui/avatar-body-list.component.tsx
src/features/edit-profile-avatar/ui/avatar-face-list.component.tsx
src/features/edit-profile-avatar/ui/done.component.tsx
src/features/edit-profile-avatar/ui/profile-avatar-edit-panel.component.tsx
src/features/edit-profile-bio/ui/v2-view.component.tsx
src/shared/ui/components/tab/tab.component.tsx
src/widgets/partyroom-edit-profile-avatar-dialog/index.ts
src/widgets/partyroom-edit-profile-avatar-dialog/ui/use-open-edit-profile-avatar-dialog.hook.tsx
src/widgets/sidebar/ui/sidebar.component.tsx

* 파티룸 내에서 사이드바에 프로필 모달 열고 아바타 세팅 클릭 시, 세팅 페이지로 이동하지 않고 다이얼로그만 띄우게 합니다.
* 프로필 세팅 패널 내 스크롤 안 먹히던 문제 등 스타일 이슈들을 함께 수정합니다

feat: 파티룸 내에서 페이지 이동 없이 아바타 설정 가능하도록 작업

---

src/entities/current-partyroom/lib/alerts/use-penalty-alert.hook.tsx
src/entities/current-partyroom/model/current-partyroom.model.ts
src/entities/current-partyroom/model/current-partyroom.store.ts
src/features/partyroom/exit/lib/use-exit-partyroom.ts
src/features/sign-out/api/use-sign-out.mutation.ts

로그아웃 하거나 패널티로 쫓겨나는 등 백단에서 exit 처리 된 경우, exit api를 클라이언트에서 또 호출하면 에러가 나므로
전역 플래그를 둬서 예외 처리 합니다.

feat: 로그아웃 하거나 패널티로 쫓겨나는 등 백단에서 exit 처리 된 경우 exit api 호출하지 않도록 설정

---

src/app/_providers/react-query.provider.tsx
src/shared/lib/react/render.ts
src/shared/ui/components/dialog/dialog.stories.tsx
src/shared/ui/components/dialog/index.ts
src/shared/ui/components/dialog/open.tsx

> 이 파일 내에서 useDialog를 사용하려면 app/logout.tsx 내 provider의 위게를 변경하여 QueryClientProvider를 DialogProvider 내부로 이동해야 하는데, 이러면 다이얼로그 body 내에서 react-query를 사용할 수 없음 (Error: No QueryClient set, use QueryClientProvider to set one). dialog를 provider가 아닌 다른 방식으로 제공하는걸 검토해봐야 할 듯
위 문제 해결을 위해 dialog를 리액트 렌더 컨텍스트 밖에서 띄우는 기능을 개발하고, 이를 react-query 전역 에러 핸들러에 연결합니다.
https://github.com/ant-design/ant-design/blob/master/components/modal/confirm.tsx

feat: dialog를 현재 리액트 렌더 컨텍스트 밖에서 띄우는 기능 개발

---

src/entities/partyroom-info/ui/form.component.tsx
src/features/partyroom/enter/lib/use-enter-partyroom.ts
src/shared/api/get-error-message.ts
src/shared/api/http/types/@shared.ts

* 파티룸 enter 중 에러 발생 시 무조건 로비로 돌려보냄
* 백엔드에 추가된 에러 코드들 enum에 반영
전역 에러(queryCache, mutationCache) 핸들러와 지역 에러간 좀 더 세밀한 핸들링이 필요합니다.
지금의 에러 처리 코드는 임시입니다. (시간상)

feat: 추가된 에러 코드 반영, 파티룸 입장 시 에러 발생하면 무조건 로비로 보내기

---

src/entities/wallet/api/use-fetch-nfts.query.ts
src/entities/wallet/api/use-update-my-walllet.mutation.ts
src/entities/wallet/index.ts
src/entities/wallet/lib/use-nfts.hook.ts
src/entities/wallet/model/nft.model.ts
src/entities/wallet/ui/connect-wallet.component.tsx
src/features/edit-profile-avatar/ui/avatar-face-list-item.component.tsx
src/features/edit-profile-avatar/ui/avatar-face-list.component.tsx
src/features/edit-profile-avatar/ui/connect-wallet-button.component.tsx

"지갑 연결"을 여러 feature에서 사용하기 위해 edit-profile-avatar feature에 있던 지갑 관련 기능을 entities로 이동합니다.
ConnectWallet 컴포넌트 뷰를 유연성 있게 확장한게 핵심 변경입니다.

refactor: "지갑 연결"을 여러 feature에서 사용하기 위해 프로필 수정 feature에 있던 지갑 관련 기능을 entities로 이동

---

src/app/(auth)/sign-in/page.tsx
src/entities/me/api/use-prefetch-me.query.ts
src/entities/me/index.ts

게스트 로그인 시에만 특정 컴포넌트의 me 호출에서 401이 나서 / 로 돌아가는데,
명확히 어떤 컴포넌트에서 me가 호출되며 원인이 뭔지 나중에 파봐야 합니다.
일단 페이지 이동 전 prefetch로 해결합니다

fix: 게스트 로그인 시 401 나면서 진입화면으로 팅기는 문제

---

src/features/playlist/move-track-to-the-other-playlist/api/use-change-track-order.mutation.ts

트랙 순서 변경마다 리스트를 refetch 하는데, #241 영상에서 보이듯 순서 변경을 빠르게 하면 refetch 도중 찰나에 또 순서 변경 시 클라이언트 측에서 변경한 상태가 refetch 결과에 의해 일순간 롤백되는 듯 보이는 문제가 있으므로 invalidate 하지 않도록 변경

chore: 플레이리스트 내 곡 순서 변경 시 리스트 refetch 안하도록 변경
